# Generated by Django 5.0.7 on 2024-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
