# Generated by Django 5.0.7 on 2024-07-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_notes_role_alter_notes_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='role',
        ),
    ]
